image_service_config:
  server: "192.168.3.99"
  port: 8080
  image_endpoint: "capture"
  visualization_endpoint: "show"

ert3_config:
  base_module: 0
  input_slot: 2
  output_slot: 3

finger_counter_config:
  thumb_length: 1.7
  index_length: 2.2
  middle_length: 2.4
  ring_length: 2.2
  pinky_length: 1.9
  visualize_data: True

min_confidence: 0.6
