version: '3.8'
services:
  my_app:
    build: .
    volumes:
      - /usr/local/lib/libm3.so.1:/usr/local/lib/libm3.so.1:ro
    devices:
      - "/dev/m3io:/dev/m3io"  # Example hardware interface
    cap_add:
      - SYS_RAWIO  # Add specific capabilities if required
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib  # Ensure Python can find the library